version: '3.0'

services:
  grafana:
    container_name: 'basic-datasource'
    build: 
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-8.3.4}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/basic-datasource,
      - ./provisioning:/etc/grafana/provisioning
