version: '3.4'

services:
  grafana:
    container_name: grafana-basic-panel
    build: .
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/basic-panel
      - ./provisioning:/etc/grafana/provisioning
